import { Roboto } from "next/font/google";
import "@/app/globals.css";
import React from "react";
import Layout from "@/core/components/layout/Layout";
import { Metadata } from "next";
import Provider from "@/core/provider/Provider";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Auto-Car",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<LayoutProps>) {
  return (
    <html lang="en" dir="ltr">
      <body className={roboto.className}>
        <Provider>
          <Layout>{children}</Layout>
        </Provider>
      </body>
    </html>
  );
}
